name: Windows dependencies

on:
  push:
    paths:
      - 'requirements.in'
      - 'requirements-dev.in'
      - 'profiles/**'
      - '.github/workflows/windows-deps.yml'
  pull_request:
    paths:
      - 'requirements.in'
      - 'requirements-dev.in'
      - 'profiles/**'
      - '.github/workflows/windows-deps.yml'
  workflow_dispatch:

jobs:
  lock:
    name: Lock dependencies (${{ matrix.profile }})
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        profile: [cpu, gpu]
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Disable line ending conversion
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Verify Python version
        run: python -c "import sys; assert sys.version_info[:2]==(3,12)"
      - name: Create virtual environment
        run: python -m venv .venv
      - name: Install pip-tools
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: pip-tools
      - name: Compile runtime lock
        if: matrix.profile == 'cpu'
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --only-binary=:all: --pip-args "--disable-pip-version-check" -o requirements.txt requirements.in
      - name: Compile dev lock
        if: matrix.profile == 'cpu'
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --only-binary=:all: --pip-args "--disable-pip-version-check" -o requirements-dev.txt requirements-dev.in
      - name: Compile Windows CPU lock
        if: matrix.profile == 'cpu'
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --only-binary=:all: --pip-args "--disable-pip-version-check" -o profiles/windows-cpu.txt profiles/windows-cpu.in
      - name: Compile Windows GPU lock
        if: matrix.profile == 'gpu'
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --only-binary=:all: --pip-args "--disable-pip-version-check --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121" -o profiles/windows-gpu.txt profiles/windows-gpu.in
      - name: Verify lock files committed (CPU)
        if: matrix.profile == 'cpu'
        run: |
          $targets = @('requirements.txt', 'requirements-dev.txt', 'profiles/windows-cpu.txt')
          $diff = git diff --name-only -- $targets
          if ($diff) {
            git --no-pager diff --stat -- $targets
            git --no-pager diff -- $targets
            Write-Error 'Windows CPU lockfiles are out of date. Regenerate them on Windows with Python 3.12 and commit the result.'
            exit 1
          }
      - name: Verify lock files committed (GPU)
        if: matrix.profile == 'gpu'
        run: |
          $target = 'profiles/windows-gpu.txt'
          if (-not (Test-Path $target)) {
            Write-Error "Expected $target to exist after compilation."
            exit 1
          }
          $diff = git diff --name-only -- $target
          if ($diff) {
            git --no-pager diff --stat -- $target
            git --no-pager diff -- $target
            Write-Error 'Windows GPU lockfile is out of date. Regenerate it on Windows with Python 3.12 and commit the result.'
            exit 1
          }

  install:
    name: Install from locks (${{ matrix.profile }})
    needs: lock
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        profile: [cpu, gpu]
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Verify Python version
        run: python -c "import sys; assert sys.version_info[:2]==(3,12)"
      - name: Create virtual environment
        run: python -m venv .venv
      - name: Install shared requirements
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: --require-hashes -r requirements.txt
      - name: Install Windows CPU lock
        if: matrix.profile == 'cpu'
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: --require-hashes -r profiles/windows-cpu.txt
      - name: Install Windows GPU lock
        if: matrix.profile == 'gpu'
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: --require-hashes --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121 -r profiles/windows-gpu.txt
      - name: Smoke import
        run: .\.venv\Scripts\python -c "import fastapi, uvicorn; print('ok')"
