name: Windows dependencies

on:
  push:
    paths:
      - 'requirements.in'
      - 'requirements-dev.in'
      - 'profiles/**'
      - '.github/workflows/windows-deps.yml'
  pull_request:
    paths:
      - 'requirements.in'
      - 'requirements-dev.in'
      - 'profiles/**'
      - '.github/workflows/windows-deps.yml'
  workflow_dispatch:

jobs:
  lock:
    name: Lock dependencies (${{ matrix.profile }})
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        profile: [cpu, gpu]
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Disable line ending conversion
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create virtual environment
        run: python -m venv .venv
      - name: Install pip-tools
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: pip-tools
      - name: Compile runtime lock
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes '--pip-args "--disable-pip-version-check --only-binary=:all:"' -o requirements.txt requirements.in
      - name: Compile dev lock
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes '--pip-args "--disable-pip-version-check --only-binary=:all:"' -o requirements-dev.txt requirements-dev.in
      - name: Compile Windows CPU lock
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes '--pip-args "--disable-pip-version-check --only-binary=:all:"' -o profiles/windows-cpu.txt profiles/windows-cpu.in
      - name: Compile Windows GPU lock
        run: .\.venv\Scripts\python -m piptools compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes '--pip-args "--disable-pip-version-check --only-binary=:all: --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121"' -o profiles/windows-gpu.txt profiles/windows-gpu.in
      - name: Verify lock files committed
        run: |
          $lockFiles = @('requirements.txt', 'requirements-dev.txt', 'profiles/windows-cpu.txt', 'profiles/windows-gpu.txt')
          $diff = git diff --name-only -- $lockFiles
          if ($diff) {
            git --no-pager diff -- $lockFiles
            exit 1
          }

  install:
    name: Install from locks (${{ matrix.profile }})
    needs: lock
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        profile: [cpu, gpu]
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create virtual environment
        run: python -m venv .venv
      - name: Install shared requirements
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: --require-hashes -r requirements.txt
      - name: Install Windows CPU lock
        if: matrix.profile == 'cpu'
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: --require-hashes -r profiles/windows-cpu.txt
      - name: Install Windows GPU lock
        if: matrix.profile == 'gpu'
        run: .\.venv\Scripts\python -m pip install --disable-pip-version-check --only-binary=:all: --require-hashes --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121 -r profiles/windows-gpu.txt
      - name: Smoke import
        run: .\.venv\Scripts\python -c "import fastapi, uvicorn; print('ok')"
