name: Windows dependencies

on:
  push:
    paths:
      - 'requirements.in'
      - 'requirements-dev.in'
      - 'profiles/**'
      - '.github/workflows/windows-deps.yml'
  pull_request:
    paths:
      - 'requirements.in'
      - 'requirements-dev.in'
      - 'profiles/**'
      - '.github/workflows/windows-deps.yml'
  workflow_dispatch:

jobs:
  lock:
    name: Lock dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Disable line ending conversion
        run: |
          git config --global core.autocrlf false
          git config --local core.autocrlf false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade pip --only-binary=:all:
          python -m pip install pip-tools --only-binary=:all:
      - name: Compile runtime lock
        run: |
          pip-compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --pip-args "--only-binary=:all: --platform win_amd64 --python-version 3.11 --implementation cp --abi cp311" --output-file requirements.txt requirements.in
      - name: Compile dev lock
        run: |
          pip-compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --pip-args "--only-binary=:all: --platform win_amd64 --python-version 3.11 --implementation cp --abi cp311" --output-file requirements-dev.txt requirements-dev.in
      - name: Compile Windows CPU lock
        run: |
          pip-compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --pip-args "--only-binary=:all: --platform win_amd64 --python-version 3.11 --implementation cp --abi cp311" --output-file profiles/windows-cpu.txt profiles/windows-cpu.in
      - name: Compile Windows GPU lock
        run: |
          pip-compile --resolver=backtracking --allow-unsafe --strip-extras --generate-hashes --pip-args "--only-binary=:all: --platform win_amd64 --python-version 3.11 --implementation cp --abi cp311 --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121" --output-file profiles/windows-gpu.txt profiles/windows-gpu.in
      - name: Check for lock drift
        run: git diff --stat
      - name: Ensure no changes
        run: git diff --exit-code

  install:
    name: Install from locks
    needs: lock
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [cpu, gpu]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create virtual environment
        run: python -m venv .venv
      - name: Upgrade pip tooling in venv
        shell: pwsh
        run: |
          .\.venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel --only-binary=:all:
      - name: Install runtime dependencies from lock
        shell: pwsh
        run: |
          .\.venv\Scripts\python.exe -m pip install --only-binary=:all: --require-hashes -r requirements.txt
      - name: Install Windows profile
        if: matrix.profile == 'cpu'
        shell: pwsh
        run: |
          .\.venv\Scripts\python.exe -m pip install --only-binary=:all: --require-hashes -r profiles/windows-cpu.txt
      - name: Install Windows GPU profile
        if: matrix.profile == 'gpu'
        shell: pwsh
        run: |
          .\.venv\Scripts\python.exe -m pip install --only-binary=:all: --require-hashes --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121 -r profiles/windows-gpu.txt
      - name: Smoke import
        shell: pwsh
        run: |
          .\.venv\Scripts\python.exe -c "import fastapi, uvicorn; print('ok')"
